server:
  port: 8087
  servlet:
    context-path: /lambda
    
spring:
  profiles:
    active: dev
  application:
    name: springboot-learning-lambda
  jackson:
    serialization:
      indent_output: true 
      
mybatis-plus:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: cn.jbinfo.learning.springboot        